/**
 * Icon Registry - Maps icon names to Lucide Svelte components
 *
 * Provides a centralized registry for icon resolution.
 * Components use string names; registry resolves to actual components.
 *
 * @example
 * import { getIcon, hasIcon } from './IconRegistry';
 * const BellIcon = getIcon('bell');
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type IconComponent = any; // Lucide exports Svelte 4 types, we accept any
import {
	// Navigation & UI
	Bell,
	BellRing,
	ChevronUp,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronsUpDown,
	Menu,
	X,
	MoreHorizontal,
	MoreVertical,
	Search,
	Filter,
	SlidersHorizontal,
	Layers,
	Layers2,
	Layers3,

	// User & Account
	User,
	Users,
	UserPlus,
	UserMinus,
	UserCheck,
	LogIn,
	LogOut,
	Settings,
	Lock,
	Unlock,
	Key,
	Shield,
	ShieldCheck,

	// Communication
	MessageCircle,
	MessageSquare,
	Mail,
	Send,
	Phone,
	Video,
	AtSign,

	// Actions
	Plus,
	Minus,
	Check,
	Copy,
	Clipboard,
	ClipboardCheck,
	Trash2,
	Edit,
	Edit2,
	Edit3,
	Save,
	Download,
	Upload,
	Share,
	Share2,
	ExternalLink,
	Link,
	Link2,
	Unlink,
	RotateCw,
	RotateCcw,
	RefreshCw,
	RefreshCcw,
	Undo2,
	Redo2,

	// Files & Folders
	File,
	FileText,
	FileCode,
	FileJson,
	Folder,
	FolderOpen,
	FolderPlus,
	FolderMinus,
	Archive,
	Package,

	// Media
	Image,
	Camera,
	Play,
	Pause,
	Square,
	Circle,
	Triangle,
	Hexagon,
	Star,
	Heart,
	ThumbsUp,
	ThumbsDown,

	// Status & Info
	Info,
	AlertCircle,
	AlertTriangle,
	CheckCircle,
	XCircle,
	HelpCircle,
	Loader2,
	Clock,
	Calendar,
	CalendarDays,

	// Layout
	LayoutDashboard,
	LayoutGrid,
	LayoutList,
	LayoutTemplate,
	Layout,
	Box,
	Boxes,
	Grid2X2,
	Grid3X3,
	Columns,
	Rows,
	Grid,
	List,
	Table,
	Kanban,
	PanelLeft,
	PanelRight,
	PanelTop,
	PanelBottom,
	PanelLeftClose,
	PanelLeftOpen,
	PanelRightClose,
	PanelRightOpen,
	Maximize,
	Minimize,
	Maximize2,
	Minimize2,

	// Code & Dev
	Code,
	Code2,
	Terminal,
	Braces,
	Bug,
	Zap,
	Cpu,
	Database,
	Server,
	Globe,
	Wifi,
	WifiOff,

	// Misc
	Home,
	Building,
	Building2,
	Briefcase,
	Tag,
	Tags,
	Bookmark,
	BookmarkPlus,
	Flag,
	Award,
	Trophy,
	Target,
	Crosshair,
	Eye,
	EyeOff,
	Sun,
	Moon,
	Cloud,
	CloudOff,
	Sparkles,
	Wand2,
	Palette,
	Paintbrush,
	Pen,
	Pencil,
	Eraser,
	Scissors,
	Move,
	GripVertical,
	GripHorizontal,
	ArrowUp,
	ArrowDown,
	ArrowLeft,
	ArrowRight,
	ArrowUpRight,
	ArrowDownLeft,
	ChevronsLeft,
	ChevronsRight,

	// Component & Tools
	Component,
	Puzzle,
	Wrench,
	FlaskConical,
	BookOpen,
	Book,
	Library,
	GitCommit,
	GitBranch,
	GitMerge,
	GitPullRequest,
	FilePlus,
	FolderGit2,
	FolderKanban,
	Replace,
	Inbox,
	Activity,
	PlusCircle,
	GraduationCap,
	Bot,
	Pin,
	PinOff,

	// Framework & Governance
	ScrollText,
	Shapes,
	Workflow,
	BadgeCheck,
	Scale,
	Network,
	ListTodo,

	// SDLC & Apps
	Rocket,
	AppWindow,
	Monitor,
	TestTube2,
	BookText,
	Lightbulb,
	CircleDashed,
	Asterisk,
	ListChecks,
	FileWarning,
	Route,
	PlayCircle,
	HeartPulse,
	ToggleLeft,
	History,
	Map,
	MapPin,
	// Text formatting (canvas inspector — B/I + alignment segments)
	Bold,
	Italic,
	AlignLeft,
	AlignCenter,
	AlignRight
} from 'lucide-svelte';

/**
 * Icon registry mapping string names to Lucide components
 * Keys use kebab-case to match Lucide naming convention
 */
const iconRegistry: Record<string, IconComponent> = {
	// Navigation & UI
	bell: Bell,
	'bell-ring': BellRing,
	'chevron-up': ChevronUp,
	'chevron-down': ChevronDown,
	'chevron-left': ChevronLeft,
	'chevron-right': ChevronRight,
	'chevrons-up-down': ChevronsUpDown,
	'chevrons-left': ChevronsLeft,
	'chevrons-right': ChevronsRight,
	menu: Menu,
	x: X,
	close: X,
	'more-horizontal': MoreHorizontal,
	'more-vertical': MoreVertical,
	search: Search,
	filter: Filter,
	'sliders-horizontal': SlidersHorizontal,
	layers: Layers,
	'layers-2': Layers2,
	'layers-3': Layers3,

	// User & Account
	user: User,
	users: Users,
	'user-plus': UserPlus,
	'user-minus': UserMinus,
	'user-check': UserCheck,
	'log-in': LogIn,
	login: LogIn,
	'log-out': LogOut,
	logout: LogOut,
	settings: Settings,
	lock: Lock,
	unlock: Unlock,
	key: Key,
	shield: Shield,
	'shield-check': ShieldCheck,

	// Communication
	'message-circle': MessageCircle,
	message: MessageCircle,
	chat: MessageCircle,
	'message-square': MessageSquare,
	mail: Mail,
	email: Mail,
	send: Send,
	phone: Phone,
	video: Video,
	'at-sign': AtSign,
	at: AtSign,

	// Actions
	plus: Plus,
	add: Plus,
	minus: Minus,
	check: Check,
	copy: Copy,
	clipboard: Clipboard,
	'clipboard-check': ClipboardCheck,
	trash: Trash2,
	'trash-2': Trash2,
	delete: Trash2,
	edit: Edit,
	'edit-2': Edit2,
	'edit-3': Edit3,
	save: Save,
	download: Download,
	upload: Upload,
	share: Share,
	'share-2': Share2,
	'external-link': ExternalLink,
	link: Link,
	'link-2': Link2,
	unlink: Unlink,
	'rotate-cw': RotateCw,
	'rotate-ccw': RotateCcw,
	'refresh-cw': RefreshCw,
	'refresh-ccw': RefreshCcw,
	refresh: RefreshCw,
	'undo-2': Undo2,
	undo: Undo2,
	'redo-2': Redo2,
	redo: Redo2,

	// Files & Folders
	file: File,
	'file-text': FileText,
	'file-code': FileCode,
	'file-json': FileJson,
	folder: Folder,
	'folder-open': FolderOpen,
	'folder-plus': FolderPlus,
	'folder-minus': FolderMinus,
	archive: Archive,
	package: Package,

	// Media
	image: Image,
	camera: Camera,
	play: Play,
	pause: Pause,
	square: Square,
	circle: Circle,
	triangle: Triangle,
	hexagon: Hexagon,
	star: Star,
	heart: Heart,
	'thumbs-up': ThumbsUp,
	'thumbs-down': ThumbsDown,
	like: ThumbsUp,
	dislike: ThumbsDown,

	// Status & Info
	info: Info,
	'alert-circle': AlertCircle,
	alert: AlertCircle,
	'alert-triangle': AlertTriangle,
	warning: AlertTriangle,
	'check-circle': CheckCircle,
	success: CheckCircle,
	'x-circle': XCircle,
	error: XCircle,
	'help-circle': HelpCircle,
	help: HelpCircle,
	'loader-2': Loader2,
	loader: Loader2,
	loading: Loader2,
	spinner: Loader2,
	clock: Clock,
	time: Clock,
	calendar: Calendar,
	'calendar-days': CalendarDays,

	// Layout
	'layout-dashboard': LayoutDashboard,
	dashboard: LayoutDashboard,
	'layout-grid': LayoutGrid,
	'layout-list': LayoutList,
	'layout-template': LayoutTemplate,
	layout: Layout,
	box: Box,
	boxes: Boxes,
	'grid-2x2': Grid2X2,
	'grid-3x3': Grid3X3,
	columns: Columns,
	rows: Rows,
	grid: Grid,
	list: List,
	table: Table,
	kanban: Kanban,
	'panel-left': PanelLeft,
	'panel-right': PanelRight,
	'panel-top': PanelTop,
	'panel-bottom': PanelBottom,
	'panel-left-close': PanelLeftClose,
	'panel-left-open': PanelLeftOpen,
	'panel-right-close': PanelRightClose,
	'panel-right-open': PanelRightOpen,
	maximize: Maximize,
	minimize: Minimize,
	'maximize-2': Maximize2,
	'minimize-2': Minimize2,

	// Code & Dev
	code: Code,
	'code-2': Code2,
	terminal: Terminal,
	braces: Braces,
	bug: Bug,
	zap: Zap,
	cpu: Cpu,
	database: Database,
	server: Server,
	globe: Globe,
	wifi: Wifi,
	'wifi-off': WifiOff,

	// Misc
	home: Home,
	building: Building,
	'building-2': Building2,
	briefcase: Briefcase,
	tag: Tag,
	tags: Tags,
	bookmark: Bookmark,
	'bookmark-plus': BookmarkPlus,
	flag: Flag,
	award: Award,
	trophy: Trophy,
	target: Target,
	crosshair: Crosshair,
	eye: Eye,
	'eye-off': EyeOff,
	sun: Sun,
	moon: Moon,
	cloud: Cloud,
	'cloud-off': CloudOff,
	sparkles: Sparkles,
	'wand-2': Wand2,
	wand: Wand2,
	magic: Wand2,
	palette: Palette,
	paintbrush: Paintbrush,
	pen: Pen,
	pencil: Pencil,
	eraser: Eraser,
	scissors: Scissors,
	move: Move,
	'grip-vertical': GripVertical,
	'grip-horizontal': GripHorizontal,
	'arrow-up': ArrowUp,
	'arrow-down': ArrowDown,
	'arrow-left': ArrowLeft,
	'arrow-right': ArrowRight,
	'arrow-up-right': ArrowUpRight,
	'arrow-down-left': ArrowDownLeft,

	// Component & Tools
	component: Component,
	puzzle: Puzzle,
	wrench: Wrench,
	tool: Wrench,
	'flask-conical': FlaskConical,
	flask: FlaskConical,
	'book-open': BookOpen,
	book: Book,
	library: Library,
	'git-commit': GitCommit,
	'git-branch': GitBranch,
	'git-merge': GitMerge,
	'git-pull-request': GitPullRequest,
	'file-plus': FilePlus,
	'folder-git-2': FolderGit2,
	'folder-git': FolderGit2,
	'folder-kanban': FolderKanban,
	replace: Replace,
	inbox: Inbox,
	activity: Activity,
	'plus-circle': PlusCircle,
	'graduation-cap': GraduationCap,
	bot: Bot,
	pin: Pin,
	'pin-off': PinOff,

	// Framework & Governance
	scroll: ScrollText,
	'scroll-text': ScrollText,
	shapes: Shapes,
	workflow: Workflow,
	'badge-check': BadgeCheck,
	scale: Scale,
	network: Network,
	'list-todo': ListTodo,

	// SDLC & Apps
	rocket: Rocket,
	'app-window': AppWindow,
	monitor: Monitor,
	'test-tube': TestTube2,
	'test-tube-2': TestTube2,
	'book-text': BookText,
	// Text formatting (canvas inspector — B/I + alignment segments)
	bold: Bold,
	italic: Italic,
	'align-left': AlignLeft,
	'align-center': AlignCenter,
	'align-right': AlignRight,
	lightbulb: Lightbulb,
	'circle-dashed': CircleDashed,
	asterisk: Asterisk,
	'list-checks': ListChecks,
	'file-warning': FileWarning,
	route: Route,
	'play-circle': PlayCircle,
	'heart-pulse': HeartPulse,
	'toggle-left': ToggleLeft,
	history: History,
	map: Map,
	'map-pin': MapPin
};

/**
 * Get an icon component by name
 * @param name - Icon name (kebab-case)
 * @returns Lucide component or undefined if not found
 */
export function getIcon(name: string): IconComponent | undefined {
	return iconRegistry[name.toLowerCase()];
}

/**
 * Check if an icon exists in the registry
 * @param name - Icon name to check
 */
export function hasIcon(name: string): boolean {
	return name.toLowerCase() in iconRegistry;
}

/**
 * Get all available icon names
 */
export function getIconNames(): string[] {
	return Object.keys(iconRegistry);
}

/**
 * Register a custom icon
 * @param name - Icon name
 * @param component - Svelte component
 */
export function registerIcon(name: string, component: IconComponent): void {
	iconRegistry[name.toLowerCase()] = component;
}

export default iconRegistry;
