// CODE GENERATED BY `sbx generate mapper` — DO NOT EDIT.
// Source:   entity.yml (platforms.go.postgres block)
// Template: go-postgres-mapper@v1
// Hash: sha256:57026403e955a9d1f3ecb25380bc8d00b1e8dba02f818af428bc99b0c2d5993a
package property

import (
	"fmt"

	"database/sql"
	"github.com/shredbx/sbx-core/pkg/repository"
	"github.com/shredbx/sbx-core/pkg/repository/postgres"
)

// Compile-time check: PostgresMapper implements postgres.Mapper[Property].
var _ postgres.Mapper[Property] = PostgresMapper{}

// Fields provides compile-time safe typed field descriptors for filtering.
var Fields = struct {
	ID              repository.Field[string]
	IsPublished     repository.Field[bool]
	ForSale         repository.Field[bool]
	ForLease        repository.Field[bool]
	PropertyType    repository.Field[string]
	SalePrice       repository.Field[int64]
	LeasePrice      repository.Field[int64]
	Furnished       repository.Field[string]
	LifecycleStatus repository.Field[string]
	SubDistrict     repository.Field[string]
	City            repository.Field[string]
	Province        repository.Field[string]
	Bedrooms        repository.Field[int]
	DeletedAt       repository.Field[string]
	CreatedAt       repository.Field[string]
}{
	ID:              repository.Field[string]{Name: "id"},
	IsPublished:     repository.Field[bool]{Name: "is_published"},
	ForSale:         repository.Field[bool]{Name: "for_sale"},
	ForLease:        repository.Field[bool]{Name: "for_lease"},
	PropertyType:    repository.Field[string]{Name: "property_type"},
	SalePrice:       repository.Field[int64]{Name: "sale_price"},
	LeasePrice:      repository.Field[int64]{Name: "lease_price"},
	Furnished:       repository.Field[string]{Name: "furnished"},
	LifecycleStatus: repository.Field[string]{Name: "lifecycle_status"},
	SubDistrict:     repository.Field[string]{Name: "sub_district"},
	City:            repository.Field[string]{Name: "city"},
	Province:        repository.Field[string]{Name: "province"},
	Bedrooms:        repository.Field[int]{Name: "bedrooms"},
	DeletedAt:       repository.Field[string]{Name: "deleted_at"},
	CreatedAt:       repository.Field[string]{Name: "created_at"},
}

// PostgresMapper implements postgres.Mapper[Property] for any PostgreSQL schema.
// Construct with NewPostgresMapper("<schema>") for the target schema.
type PostgresMapper struct {
	schema string
}

// NewPostgresMapper creates a mapper scoped to the given PostgreSQL schema.
func NewPostgresMapper(schema string) PostgresMapper {
	return PostgresMapper{schema: schema}
}

func (m PostgresMapper) tbl(name string) string {
	return fmt.Sprintf("%s.%s", m.schema, name)
}

// TableName returns the primary table for INSERT/UPDATE/DELETE.
func (m PostgresMapper) TableName() string {
	return m.tbl("properties")
}

// SelectFrom returns the FROM clause with LEFT JOINs for attribute-group tables.
func (m PostgresMapper) SelectFrom() string {
	return fmt.Sprintf(`%s p
LEFT JOIN %s loc ON loc.property_id = p.id
LEFT JOIN %s sz ON sz.property_id = p.id
LEFT JOIN %s rm ON rm.property_id = p.id`,
		m.tbl("properties"),
		m.tbl("property_locations"),
		m.tbl("property_sizes"),
		m.tbl("property_rooms"),
	)
}

// Columns returns the SELECT column list. Order must exactly match FromRow scan.
func (m PostgresMapper) Columns() []string {
	return []string{
		// properties (31)
		"p.id",
		"p.title",
		"p.slug",
		"p.title_deed",
		"p.title_deed_raw",
		"p.text",
		"p.translations",
		"p.property_type",
		"p.is_published",
		"p.for_sale",
		"p.for_lease",
		"p.sale_price",
		"p.lease_price",
		"p.price_currency",
		"p.cover_image_id",
		"p.landlord_contact_id",
		"p.listing_agent_id",
		"p.furnished",
		"p.lifecycle_status",
		"p.ownership_type",
		"p.condition",
		"p.direction",
		"p.road_access",
		"p.topography",
		"p.rank",
		"p.location_public",
		"p.plot_public",
		"p.policies_public",
		"p.created_at",
		"p.updated_at",
		"p.deleted_at",
		// property_locations (12)
		"loc.street",
		"loc.unit",
		"loc.sub_district",
		"loc.city",
		"loc.province",
		"loc.postal_code",
		"loc.country",
		"loc.latitude",
		"loc.longitude",
		"loc.polygon",
		"loc.location_map_view",
		"loc.region_map_view",
		// property_sizes (6)
		"sz.land_size",
		"sz.house_size",
		"sz.living_size",
		"sz.total_area",
		"sz.usable_area",
		"sz.balcony_area",
		// property_rooms (9)
		"rm.bedrooms",
		"rm.bathrooms",
		"rm.kitchens",
		"rm.living_rooms",
		"rm.dining_rooms",
		"rm.offices",
		"rm.storage_rooms",
		"rm.maid_rooms",
		"rm.guest_rooms",
	}
}

// FieldColumn maps logical field names to aliased column names for WHERE clauses.
func (m PostgresMapper) FieldColumn(field string) string {
	switch field {
	case "bathrooms":
		return "rm.bathrooms"
	case "bedrooms":
		return "rm.bedrooms"
	case "city":
		return "loc.city"
	case "country":
		return "loc.country"
	case "cover_image_id":
		return "p.cover_image_id"
	case "created_at":
		return "p.created_at"
	case "deleted_at":
		return "p.deleted_at"
	case "for_lease":
		return "p.for_lease"
	case "for_sale":
		return "p.for_sale"
	case "furnished":
		return "p.furnished"
	case "id":
		return "p.id"
	case "is_published":
		return "p.is_published"
	case "landlord_contact_id":
		return "p.landlord_contact_id"
	case "lease_price":
		return "p.lease_price"
	case "listing_agent_id":
		return "p.listing_agent_id"
	case "price_currency":
		return "p.price_currency"
	case "property_type":
		return "p.property_type"
	case "province":
		return "loc.province"
	case "rank":
		return "p.rank"
	case "sale_price":
		return "p.sale_price"
	case "slug":
		return "p.slug"
	case "sub_district":
		return "loc.sub_district"
	case "title":
		return "p.title"
	case "updated_at":
		return "p.updated_at"
	default:
		return field
	}
}

// ToRow converts a Property to a column→value map for INSERT/UPDATE.
// Only primary-table columns — not joined attribute-group tables.
func (m PostgresMapper) ToRow(p Property) (map[string]any, error) {
	var titleDeed *string
	if p.TitleDeed != nil {
		s := string(*p.TitleDeed)
		titleDeed = &s
	}
	var propertyType *string
	if p.PropertyType != nil {
		s := string(*p.PropertyType)
		propertyType = &s
	}
	var furnished *string
	if p.Furnished != nil {
		s := string(*p.Furnished)
		furnished = &s
	}
	var ownership *string
	if p.Ownership != nil {
		s := string(*p.Ownership)
		ownership = &s
	}
	var condition *string
	if p.Condition != nil {
		s := string(*p.Condition)
		condition = &s
	}
	var direction *string
	if p.Direction != nil {
		s := string(*p.Direction)
		direction = &s
	}
	var roadAccess *string
	if p.RoadAccess != nil {
		s := string(*p.RoadAccess)
		roadAccess = &s
	}
	var topography *string
	if p.Topography != nil {
		s := string(*p.Topography)
		topography = &s
	}
	return map[string]any{
		"id":                  p.ID,
		"title":               p.Title,
		"slug":                p.Slug,
		"title_deed":          titleDeed,
		"title_deed_raw":      p.TitleDeedRaw,
		"text":                p.Text,
		"translations":        p.Translations,
		"property_type":       propertyType,
		"is_published":        p.IsPublished,
		"for_sale":            p.ForSale,
		"for_lease":           p.ForLease,
		"sale_price":          p.SalePrice,
		"lease_price":         p.LeasePrice,
		"price_currency":      p.PriceCurrency,
		"cover_image_id":      p.CoverImageID,
		"landlord_contact_id": p.LandlordContactID,
		"listing_agent_id":    p.ListingAgentID,
		"furnished":           furnished,
		"lifecycle_status":    p.LifecycleStatus,
		"ownership_type":      ownership,
		"condition":           condition,
		"direction":           direction,
		"road_access":         roadAccess,
		"topography":          topography,
		"rank":                p.Rank,
		"location_public":     p.LocationPublic,
		"plot_public":         p.PlotPublic,
		"policies_public":     p.PoliciesPublic,
		"created_at":          p.CreatedAt,
		"updated_at":          p.UpdatedAt,
	}, nil
}

// FromRow scans a row (including JOIN columns) into a Property.
// Column order must exactly match Columns().
func (m PostgresMapper) FromRow(scan func(dest ...any) error) (Property, error) {
	var p Property
	var addressStreet sql.NullString
	var addressUnit sql.NullString
	var addressSubDistrict sql.NullString
	var addressCity sql.NullString
	var addressProvince sql.NullString
	var addressPostalCode sql.NullString
	var addressCountry sql.NullString
	var addressLatitude sql.NullFloat64
	var addressLongitude sql.NullFloat64
	var addressPolygon GeoJSONPolygon
	var addressLocationMapView MapView
	var addressRegionMapView MapView
	var sizes Sizes
	var rooms Rooms

	var titleDeed *string
	var propertyType *string
	var furnished *string
	var ownership *string
	var condition *string
	var direction *string
	var roadAccess *string
	var topography *string

	err := scan(
		&p.ID,
		&p.Title,
		&p.Slug,
		&titleDeed,
		&p.TitleDeedRaw,
		&p.Text,
		&p.Translations,
		&propertyType,
		&p.IsPublished,
		&p.ForSale,
		&p.ForLease,
		&p.SalePrice,
		&p.LeasePrice,
		&p.PriceCurrency,
		&p.CoverImageID,
		&p.LandlordContactID,
		&p.ListingAgentID,
		&furnished,
		&p.LifecycleStatus,
		&ownership,
		&condition,
		&direction,
		&roadAccess,
		&topography,
		&p.Rank,
		&p.LocationPublic,
		&p.PlotPublic,
		&p.PoliciesPublic,
		&p.CreatedAt,
		&p.UpdatedAt,
		&p.DeletedAt,
		// property_locations
		&addressStreet,
		&addressUnit,
		&addressSubDistrict,
		&addressCity,
		&addressProvince,
		&addressPostalCode,
		&addressCountry,
		&addressLatitude,
		&addressLongitude,
		&addressPolygon,
		&addressLocationMapView,
		&addressRegionMapView,
		// property_sizes
		&sizes.LandSize,
		&sizes.HouseSize,
		&sizes.LivingSize,
		&sizes.TotalArea,
		&sizes.UsableArea,
		&sizes.BalconyArea,
		// property_rooms
		&rooms.Bedrooms,
		&rooms.Bathrooms,
		&rooms.Kitchens,
		&rooms.LivingRooms,
		&rooms.DiningRooms,
		&rooms.Offices,
		&rooms.StorageRooms,
		&rooms.MaidRooms,
		&rooms.GuestRooms,
	)
	if err != nil {
		return p, err
	}
	if titleDeed != nil {
		v := TitleDeed(*titleDeed)
		p.TitleDeed = &v
	}
	if propertyType != nil {
		v := PropertyType(*propertyType)
		p.PropertyType = &v
	}
	if furnished != nil {
		v := Furnished(*furnished)
		p.Furnished = &v
	}
	if ownership != nil {
		v := Ownership(*ownership)
		p.Ownership = &v
	}
	if condition != nil {
		v := Condition(*condition)
		p.Condition = &v
	}
	if direction != nil {
		v := Direction(*direction)
		p.Direction = &v
	}
	if roadAccess != nil {
		v := RoadAccess(*roadAccess)
		p.RoadAccess = &v
	}
	if topography != nil {
		v := Topography(*topography)
		p.Topography = &v
	}

	var address Address
	address.Street = addressStreet.String
	address.Unit = addressUnit.String
	address.SubDistrict = addressSubDistrict.String
	address.City = addressCity.String
	address.Province = addressProvince.String
	address.PostalCode = addressPostalCode.String
	address.Country = addressCountry.String
	address.Latitude = addressLatitude.Float64
	address.Longitude = addressLongitude.Float64
	address.Polygon = addressPolygon
	address.LocationMapView = addressLocationMapView
	address.RegionMapView = addressRegionMapView
	p.Address = address
	p.Sizes = &sizes
	p.Rooms = &rooms

	return p, nil
}
