services:

  chat-api-postgres:
    image: postgres:16
    container_name: chat-api-postgres-chat-api-postgres
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

