// CODE GENERATED BY `sbx generate mapper` — DO NOT EDIT.
// Source:   entity.yml (platforms.go.postgres block)
// Template: go-postgres-mapper@v1
// Hash: sha256:b6fe043c40f5d499fd8639052ab4962a484f080995ba5b70679c898045280b30
package contact

import (
	"fmt"

	"github.com/shredbx/sbx-core/pkg/repository"
	"github.com/shredbx/sbx-core/pkg/repository/postgres"
)

// Compile-time check: PostgresMapper implements postgres.Mapper[Contact].
var _ postgres.Mapper[Contact] = PostgresMapper{}

// Fields provides compile-time safe typed field descriptors for filtering.
var Fields = struct {
	ID          repository.Field[string]
	Email       repository.Field[string]
	GivenName   repository.Field[string]
	Surname     repository.Field[string]
	PhoneNumber repository.Field[string]
	City        repository.Field[string]
	Country     repository.Field[string]
	DeletedAt   repository.Field[string]
	CreatedAt   repository.Field[string]
}{
	ID:          repository.Field[string]{Name: "id"},
	Email:       repository.Field[string]{Name: "email"},
	GivenName:   repository.Field[string]{Name: "given_name"},
	Surname:     repository.Field[string]{Name: "surname"},
	PhoneNumber: repository.Field[string]{Name: "phone_number"},
	City:        repository.Field[string]{Name: "city"},
	Country:     repository.Field[string]{Name: "country"},
	DeletedAt:   repository.Field[string]{Name: "deleted_at"},
	CreatedAt:   repository.Field[string]{Name: "created_at"},
}

// PostgresMapper implements postgres.Mapper[Contact] for any PostgreSQL schema.
// Construct with NewPostgresMapper("<schema>") for the target schema.
type PostgresMapper struct {
	schema string
}

// NewPostgresMapper creates a mapper scoped to the given PostgreSQL schema.
func NewPostgresMapper(schema string) PostgresMapper {
	return PostgresMapper{schema: schema}
}

func (m PostgresMapper) tbl(name string) string {
	return fmt.Sprintf("%s.%s", m.schema, name)
}

// TableName returns the primary table for INSERT/UPDATE/DELETE.
func (m PostgresMapper) TableName() string {
	return m.tbl("contacts")
}

// SelectFrom returns the primary table aliased for SELECT — Columns() prefixes
// every field with the primary alias, so the FROM clause must publish it.
func (m PostgresMapper) SelectFrom() string {
	return m.TableName() + " c"
}

// Columns returns the SELECT column list. Order must exactly match FromRow scan.
func (m PostgresMapper) Columns() []string {
	return []string{
		// contacts (26)
		"c.id",
		"c.title",
		"c.given_name",
		"c.middle_name",
		"c.surname",
		"c.date_of_birth",
		"c.nationality",
		"c.email",
		"c.phone_country_code",
		"c.phone_number",
		"c.phone_type",
		"c.street",
		"c.unit",
		"c.sub_district",
		"c.city",
		"c.province",
		"c.postal_code",
		"c.country",
		"c.latitude",
		"c.longitude",
		"c.social_networks",
		"c.data",
		"c.photo_id",
		"c.created_at",
		"c.updated_at",
		"c.deleted_at",
	}
}

// FieldColumn maps logical field names to aliased column names for WHERE clauses.
func (m PostgresMapper) FieldColumn(field string) string {
	switch field {
	case "city":
		return "c.city"
	case "country":
		return "c.country"
	case "created_at":
		return "c.created_at"
	case "deleted_at":
		return "c.deleted_at"
	case "email":
		return "c.email"
	case "given_name":
		return "c.given_name"
	case "id":
		return "c.id"
	case "phone_number":
		return "c.phone_number"
	case "surname":
		return "c.surname"
	default:
		return field
	}
}

// ToRow converts a Contact to a column→value map for INSERT/UPDATE.
// Only primary-table columns — not joined attribute-group tables.
func (m PostgresMapper) ToRow(p Contact) (map[string]any, error) {
	return map[string]any{
		"id":                 p.ID,
		"title":              p.Title,
		"given_name":         p.GivenName,
		"middle_name":        p.MiddleName,
		"surname":            p.Surname,
		"date_of_birth":      p.DateOfBirth,
		"nationality":        p.Nationality,
		"email":              p.Email,
		"phone_country_code": p.PhoneCountryCode,
		"phone_number":       p.PhoneNumber,
		"phone_type":         p.PhoneType,
		"street":             p.Street,
		"unit":               p.Unit,
		"sub_district":       p.SubDistrict,
		"city":               p.City,
		"province":           p.Province,
		"postal_code":        p.PostalCode,
		"country":            p.Country,
		"latitude":           p.Latitude,
		"longitude":          p.Longitude,
		"social_networks":    p.SocialNetworks,
		"data":               p.Data,
		"photo_id":           p.PhotoID,
		"created_at":         p.CreatedAt,
		"updated_at":         p.UpdatedAt,
	}, nil
}

// FromRow scans a row (including JOIN columns) into a Contact.
// Column order must exactly match Columns().
func (m PostgresMapper) FromRow(scan func(dest ...any) error) (Contact, error) {
	var p Contact

	err := scan(
		&p.ID,
		&p.Title,
		&p.GivenName,
		&p.MiddleName,
		&p.Surname,
		&p.DateOfBirth,
		&p.Nationality,
		&p.Email,
		&p.PhoneCountryCode,
		&p.PhoneNumber,
		&p.PhoneType,
		&p.Street,
		&p.Unit,
		&p.SubDistrict,
		&p.City,
		&p.Province,
		&p.PostalCode,
		&p.Country,
		&p.Latitude,
		&p.Longitude,
		&p.SocialNetworks,
		&p.Data,
		&p.PhotoID,
		&p.CreatedAt,
		&p.UpdatedAt,
		&p.DeletedAt,
	)
	if err != nil {
		return p, err
	}

	return p, nil
}
