// CODE GENERATED BY `sbx generate mapper` — DO NOT EDIT.
// Source:   entity.yml (platforms.go.postgres block)
// Template: go-postgres-mapper@v1
// Hash: sha256:28d6597b873dc40907b55d481e223c9f4a06945f3f489d5e999940e37c879a01
package transaction

import (
	"fmt"

	"github.com/shredbx/sbx-core/pkg/repository"
	"github.com/shredbx/sbx-core/pkg/repository/postgres"
)

// Compile-time check: PostgresMapper implements postgres.Mapper[Transaction].
var _ postgres.Mapper[Transaction] = PostgresMapper{}

// Fields provides compile-time safe typed field descriptors for filtering.
var Fields = struct {
	ID         repository.Field[string]
	Type       repository.Field[string]
	Status     repository.Field[string]
	ClosedAs   repository.Field[string]
	PropertyID repository.Field[string]
	UnitID     repository.Field[string]
	OpenedAt   repository.Field[string]
	ClosedAt   repository.Field[string]
}{
	ID:         repository.Field[string]{Name: "id"},
	Type:       repository.Field[string]{Name: "type"},
	Status:     repository.Field[string]{Name: "status"},
	ClosedAs:   repository.Field[string]{Name: "closed_as"},
	PropertyID: repository.Field[string]{Name: "property_id"},
	UnitID:     repository.Field[string]{Name: "unit_id"},
	OpenedAt:   repository.Field[string]{Name: "opened_at"},
	ClosedAt:   repository.Field[string]{Name: "closed_at"},
}

// PostgresMapper implements postgres.Mapper[Transaction] for any PostgreSQL schema.
// Construct with NewPostgresMapper("<schema>") for the target schema.
type PostgresMapper struct {
	schema string
}

// NewPostgresMapper creates a mapper scoped to the given PostgreSQL schema.
func NewPostgresMapper(schema string) PostgresMapper {
	return PostgresMapper{schema: schema}
}

func (m PostgresMapper) tbl(name string) string {
	return fmt.Sprintf("%s.%s", m.schema, name)
}

// TableName returns the primary table for INSERT/UPDATE/DELETE.
func (m PostgresMapper) TableName() string {
	return m.tbl("transactions")
}

// SelectFrom returns the primary table aliased for SELECT — Columns() prefixes
// every field with the primary alias, so the FROM clause must publish it.
func (m PostgresMapper) SelectFrom() string {
	return m.TableName() + " t"
}

// Columns returns the SELECT column list. Order must exactly match FromRow scan.
func (m PostgresMapper) Columns() []string {
	return []string{
		// transactions (12)
		"t.id",
		"t.type",
		"t.status",
		"t.closed_as",
		"t.property_id",
		"t.unit_id",
		"t.lease_duration",
		"t.lease_start",
		"t.lease_end",
		"t.opened_at",
		"t.closed_at",
		"t.notes",
	}
}

// FieldColumn maps logical field names to aliased column names for WHERE clauses.
func (m PostgresMapper) FieldColumn(field string) string {
	switch field {
	case "closed_as":
		return "t.closed_as"
	case "closed_at":
		return "t.closed_at"
	case "id":
		return "t.id"
	case "opened_at":
		return "t.opened_at"
	case "property_id":
		return "t.property_id"
	case "status":
		return "t.status"
	case "type":
		return "t.type"
	case "unit_id":
		return "t.unit_id"
	default:
		return field
	}
}

// ToRow converts a Transaction to a column→value map for INSERT/UPDATE.
// Only primary-table columns — not joined attribute-group tables.
func (m PostgresMapper) ToRow(p Transaction) (map[string]any, error) {
	var closedAs *string
	if p.ClosedAs != nil {
		s := string(*p.ClosedAs)
		closedAs = &s
	}
	return map[string]any{
		"id":             p.ID,
		"type":           p.Type,
		"status":         p.Status,
		"closed_as":      closedAs,
		"property_id":    p.PropertyID,
		"unit_id":        p.UnitID,
		"lease_duration": p.LeaseTerm,
		"lease_start":    p.LeaseStart,
		"lease_end":      p.LeaseEnd,
		"opened_at":      p.OpenedAt,
		"closed_at":      p.ClosedAt,
		"notes":          p.Notes,
	}, nil
}

// FromRow scans a row (including JOIN columns) into a Transaction.
// Column order must exactly match Columns().
func (m PostgresMapper) FromRow(scan func(dest ...any) error) (Transaction, error) {
	var p Transaction

	var closedAs *string

	err := scan(
		&p.ID,
		&p.Type,
		&p.Status,
		&closedAs,
		&p.PropertyID,
		&p.UnitID,
		&p.LeaseTerm,
		&p.LeaseStart,
		&p.LeaseEnd,
		&p.OpenedAt,
		&p.ClosedAt,
		&p.Notes,
	)
	if err != nil {
		return p, err
	}
	if closedAs != nil {
		v := Facet(*closedAs)
		p.ClosedAs = &v
	}

	return p, nil
}
