// CODE GENERATED BY `sbx generate currencies` — DO NOT EDIT.
// Source:   .sbx/workspace/packages/core/go/types/money/currencies.yml
// Template: currencies@v1
// Hash: sha256:07307c1aac2d9911000672724111e754dae1b6c55f6abc83490948dbac5d0af6
package money

// generatedCurrencies is the governed currency table, projected from the
// currencies.yml dictionary. init() registers these into the runtime registry.
var generatedCurrencies = []Currency{
	{Code: "AUD", Symbol: "A$", Name: "Australian Dollar", Decimals: 2, SymbolPosition: "prefix"},
	{Code: "CNY", Symbol: "¥", Name: "Chinese Yuan", Decimals: 2, SymbolPosition: "prefix"},
	{Code: "EUR", Symbol: "€", Name: "Euro", Decimals: 2, SymbolPosition: "suffix"},
	{Code: "GBP", Symbol: "£", Name: "British Pound", Decimals: 2, SymbolPosition: "prefix"},
	{Code: "JPY", Symbol: "¥", Name: "Japanese Yen", Decimals: 0, SymbolPosition: "prefix"},
	{Code: "RUB", Symbol: "₽", Name: "Russian Ruble", Decimals: 2, SymbolPosition: "suffix"},
	{Code: "THB", Symbol: "฿", Name: "Thai Baht", Decimals: 2, SymbolPosition: "prefix"},
	{Code: "USD", Symbol: "$", Name: "US Dollar", Decimals: 2, SymbolPosition: "prefix"},
}
