// CODE GENERATED BY `sbx generate currencies` — DO NOT EDIT.
// Source:   .sbx/workspace/packages/core/go/types/money/currencies.yml
// Template: currencies@v1
// Hash: sha256:07307c1aac2d9911000672724111e754dae1b6c55f6abc83490948dbac5d0af6

/** Currency display configuration (projected from currencies.yml). */
export interface CurrencyConfig {
	code: string;
	/** ISO 4217 numeric-3 code, zero-padded. */
	numeric: string;
	symbol: string;
	name: string;
	decimals: number;
	symbolPosition: 'prefix' | 'suffix';
	/** live = primary settlement currency, listed = selectable/displayable. */
	status: 'live' | 'listed';
}

/** Governed currency registry — single source of truth (currencies.yml). */
export const CURRENCIES: Record<string, CurrencyConfig> = {
	AUD: { code: "AUD", numeric: "036", symbol: "A$", name: "Australian Dollar", decimals: 2, symbolPosition: "prefix", status: "listed" },
	CNY: { code: "CNY", numeric: "156", symbol: "¥", name: "Chinese Yuan", decimals: 2, symbolPosition: "prefix", status: "listed" },
	EUR: { code: "EUR", numeric: "978", symbol: "€", name: "Euro", decimals: 2, symbolPosition: "suffix", status: "listed" },
	GBP: { code: "GBP", numeric: "826", symbol: "£", name: "British Pound", decimals: 2, symbolPosition: "prefix", status: "listed" },
	JPY: { code: "JPY", numeric: "392", symbol: "¥", name: "Japanese Yen", decimals: 0, symbolPosition: "prefix", status: "listed" },
	RUB: { code: "RUB", numeric: "643", symbol: "₽", name: "Russian Ruble", decimals: 2, symbolPosition: "suffix", status: "listed" },
	THB: { code: "THB", numeric: "764", symbol: "฿", name: "Thai Baht", decimals: 2, symbolPosition: "prefix", status: "live" },
	USD: { code: "USD", numeric: "840", symbol: "$", name: "US Dollar", decimals: 2, symbolPosition: "prefix", status: "listed" },
};
